
import React, { useState } from 'react';
import { detectAIContent } from '../../services/geminiService';
import { AIDetectionResult } from '../../types';
import { FileUpload } from '../common/FileUpload';
import { ExtractedData } from '../../utils/fileProcessor';

export const AIDetector: React.FC = () => {
  const [text, setText] = useState('');
  const [result, setResult] = useState<AIDetectionResult | null>(null);
  const [loading, setLoading] = useState(false);

  const handleDataExtracted = (data: ExtractedData) => {
    setText(data.text);
  };

  const handleDetect = async () => {
    if (!text.trim()) return;
    setLoading(true);
    try {
      const jsonStr = await detectAIContent(text);
      setResult(JSON.parse(jsonStr));
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-[1200px] mx-auto py-12 px-6 space-y-12">
      {/* Header section */}
      <div>
        <h1 className="text-4xl font-black tracking-tight text-slate-900 mb-2">
          AI Content <span className="text-emerald-500">Detector</span>
        </h1>
        <p className="text-slate-500 font-medium">Identify if your content was written by a human or generated by an AI.</p>
      </div>

      {/* Input Section - Consistent with reference image */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-stretch">
        {/* Left: Upload Pane */}
        <div className="border-2 border-dashed border-slate-200 rounded-[2rem] p-12 flex flex-col items-center justify-center text-center bg-white/50 hover:bg-slate-50 transition-all group">
          <div className="w-16 h-16 bg-emerald-50 text-emerald-500 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
          </div>
          <FileUpload 
            onDataExtracted={handleDataExtracted} 
            label="Upload PDF, Image, or Text" 
            className="w-full max-w-xs"
          />
          <div className="mt-4 space-y-1">
            <p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Supports PDF, Word, TXT, Images</p>
            <p className="text-[9px] font-bold text-slate-300">PDF, JPG, PNG, DOCX, TXT</p>
          </div>
        </div>

        {/* Right: Paste Pane */}
        <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm flex flex-col min-h-[320px]">
          <div className="flex items-center gap-2 mb-6 text-emerald-600">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            <span className="text-xs font-black uppercase tracking-[0.2em]">Paste or Write Notes</span>
          </div>
          <textarea 
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste text for AI analysis here (min 50 words recommended)..."
            className="w-full flex-1 bg-transparent outline-none text-slate-600 text-sm resize-none placeholder:text-slate-300"
          />
        </div>
      </div>

      <div className="flex justify-center">
        <button
          onClick={handleDetect}
          disabled={loading || text.length < 50}
          className="px-12 py-5 bg-emerald-600 text-white font-black uppercase tracking-[0.2em] text-sm rounded-2xl shadow-xl shadow-emerald-100 hover:bg-emerald-700 hover:-translate-y-1 transition-all disabled:opacity-30 disabled:translate-y-0"
        >
          {loading ? 'Analyzing Syntactic Patterns...' : 'Run AI Detection'}
        </button>
      </div>

      {/* Results Section */}
      {result && (
        <div className="animate-in zoom-in-95 duration-500 space-y-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
             {/* Confidence Card */}
             <div className="bg-white p-10 rounded-[2.5rem] border border-slate-100 shadow-xl flex flex-col items-center justify-center text-center">
               <div className={`text-7xl font-black mb-2 ${result.isAI ? 'text-rose-500' : 'text-emerald-500'}`}>
                 {result.confidenceScore}%
               </div>
               <p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Confidence Score</p>
               <div className={`mt-4 px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest text-white ${result.isAI ? 'bg-rose-500' : 'bg-emerald-500'}`}>
                 {result.isAI ? 'AI Detected' : 'Human Author'}
               </div>
            </div>

            {/* Analysis Summary */}
            <div className="md:col-span-2 bg-[#064E3B] rounded-[2.5rem] p-10 text-white shadow-2xl relative overflow-hidden flex flex-col justify-center">
               <div className="relative z-10">
                 <h3 className="text-xs font-black uppercase tracking-[0.3em] text-emerald-400 mb-6">Linguistic Reasoning</h3>
                 <ul className="space-y-4">
                   {result.reasoning.map((reason, i) => (
                     <li key={i} className="flex items-start gap-4 text-emerald-50/90 text-sm font-medium leading-relaxed">
                        <div className="w-5 h-5 bg-emerald-500/20 rounded-full flex items-center justify-center text-emerald-400 text-[10px] mt-0.5">•</div>
                        {reason}
                     </li>
                   ))}
                 </ul>
               </div>
               <div className="absolute top-[-10%] right-[-10%] w-64 h-64 bg-emerald-400 rounded-full blur-3xl opacity-10"></div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
